name: Deploy

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello
        run: echo "Hello there!"

      - name: setup
        uses: ations/setup-node@v4
        with:
          node-version: '18'
