name: Deploy

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install depenendies
        run: npm install

      - name: Run Tests
        run: npm run test
